apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-eip.fullname" . }}
  labels:
    {{- include "k8s-eip.labels" . | nindent 4 }}
type: Opaque
data:
  aws-access-key: {{ required ".Values.awsAccessKeyId required" .Values.awsAccessKeyId | b64enc | quote }}
  aws-secret-key: {{ required ".Values.awsSecretAccessKey required" .Values.awsSecretAccessKey | b64enc | quote }}
